name: CICD Pipeline

on: [push]
  
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
     - name: Run the script
     - uses: actions/checkout@v2
     - run: python hello.py
  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the file
      - uses: actions/checkout@v2
      
      - name: Create the artifact
      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: .
